(function () {
  'use strict';
  const Finance = window.WealthDomain;
  const storageKey = 'wealthpilot-independent-workspace-v1';
  const palette = ['#325cf4', '#ef6870', '#f0b83e', '#8b65cc', '#39a0b5', '#ec8b43', '#6d81ae', '#c466a3'];
  const routes = { today: ["Aujourd'hui", 'layout-dashboard'], history: ['Historique', 'list-filter'], budget: ['Budget', 'chart-column'], analytics: ['Analyse', 'chart-no-axes-combined'], sharing: ['Partage', 'users'], recurring: ['Récurrents', 'repeat-2'], accounts: ['Comptes', 'wallet'], import: ['Importer un CSV', 'file-up'], settings: ['Foyer et sauvegardes', 'settings-2'] };
  const categoryIcons = { Logement: 'house', Alimentation: 'shopping-basket', Transport: 'car-front', Restaurants: 'utensils', Santé: 'heart-pulse', Loisirs: 'ticket', Abonnements: 'repeat-2', Achats: 'shopping-bag', Revenus: 'briefcase-business', 'À classer': 'circle-help' };
  const main = document.getElementById('main');
  const chartRegistry = new Map(), chartTables = new Map(), selections = new Map(), drafts = new Map(), scrollPositions = new Map();
  let state, view = 'today', scope = 'all', preset = 'month', privacy = false, query = '', categoryFilter = '', historyType = 'all', pageIndex = 0, editor = null, auxiliary = null, pendingAction = null, importDraft = null, restoreCandidate = null, noticeTimer;
  const grains = {};
  let weekOffset = 0;
  let importSequence = 0;
  const layoutKey = 'wealthpilot-dashboard-layout-v1';
  const widgets = { 'balance-card': 'Solde des comptes', 'week-card': 'Dépenses de la semaine', 'budget-card': 'Budget disponible', 'income-card': 'Revenus importés', 'expenses-card': 'Dépenses importées', 'net-card': 'Revenus − dépenses', balance: 'Évolution du solde', week: 'Dépenses de la semaine', categories: 'Dépenses par catégorie', envelopes: 'Enveloppes', quality: 'Qualité des relevés', recent: 'Dernières opérations', expenses: 'Dépenses dans le temps', 'analysis-categories': 'Dépenses par catégorie', days: 'Dépenses par jour', merchants: 'Dépenses par marchand', monthly: 'Bilan mensuel' };
  const defaultLayout = { today: ['balance-card', 'week-card', 'budget-card', 'balance', 'week', 'categories', 'envelopes', 'quality', 'recent'], analytics: ['income-card', 'expenses-card', 'net-card', 'expenses', 'analysis-categories', 'days'], widths: {}, variants: {} };
  const availableWidgets = { today: [...defaultLayout.today, 'merchants', 'monthly'], analytics: [...defaultLayout.analytics, 'merchants', 'monthly'] };
  const variants = { balance: [['line', 'Courbe'], ['bar', 'Barres']], expenses: [['bar', 'Barres'], ['line', 'Courbe']], envelopes: [['bars', 'Barres'], ['rings', 'Anneaux'], ['table', 'Tableau']], categories: [['ring', 'Anneau'], ['list', 'Liste']], 'analysis-categories': [['ring', 'Anneau'], ['list', 'Liste']] };
  let layout = structuredClone(defaultLayout), customizing = false;
  try { const stored = JSON.parse(localStorage.getItem(layoutKey)); if (stored && Object.keys(availableWidgets).every(route => Array.isArray(stored[route]) && stored[route].length && new Set(stored[route]).size === stored[route].length && stored[route].every(id => availableWidgets[route].includes(id)))) { layout.today = stored.today; layout.analytics = stored.analytics; for (const [id, width] of Object.entries(stored.widths || {})) if (widgets[id] && [4, 6, 8, 12].includes(width)) layout.widths[id] = width; for (const [id, variant] of Object.entries(stored.variants || {})) if (variants[id]?.some(([key]) => key === variant)) layout.variants[id] = variant; } } catch {}
  function saveLayout(mutator) { const next = structuredClone(layout); mutator(next); localStorage.setItem(layoutKey, JSON.stringify(next)); layout = next; render(); }
  function optionalWidget(id) {
    if (id === 'merchants') return panel(id, widgets[id], chartNode(id, 'Dépenses par marchand'), 6, chartActions(id, false));
    const months = Finance.metrics(state, context('month')).series;
    return panel('monthly', 'Bilan mensuel', `<div class="table-scroll"><table><thead><tr><th>Mois</th><th class="amount">Revenus</th><th class="amount">Dépenses</th><th class="amount">Différence</th></tr></thead><tbody>${months.map(item => `<tr><td>${bucketLabel(item, 'month')}</td><td class="amount money">${money(item.income)}</td><td class="amount money">${money(item.expenses)}</td><td class="amount money">${money(item.income - item.expenses)}</td></tr>`).join('')}</tbody></table></div>`, 12);
  }
  function arrangeModules(markup) {
    if (!availableWidgets[view]) return markup;
    const template = document.createElement('template'); template.innerHTML = markup;
    const grid = template.content.querySelector('.grid');
    if (view === 'today') { [...grid.children].slice(0, 3).forEach((element, index) => { element.id = `component-${defaultLayout.today[index]}`; }); grid.lastElementChild.id = 'component-recent'; }
    if (view === 'analytics') [...grid.children].slice(0, 3).forEach((element, index) => { element.id = `component-${defaultLayout.analytics[index]}`; });
    for (const id of availableWidgets[view]) if (!template.content.querySelector(`#component-${id}`)) grid.insertAdjacentHTML('beforeend', optionalWidget(id));
    const modules = new Map([...grid.children].map(element => [element.id.replace('component-', ''), element]));
    grid.replaceChildren();
    for (const [index, id] of layout[view].entries()) {
      const element = modules.get(id); if (!element) continue;
      if (layout.widths[id]) { for (const name of [...element.classList]) if (name.startsWith('span-')) element.classList.remove(name); element.classList.add(`span-${layout.widths[id]}`); }
      if (customizing) element.insertAdjacentHTML('afterbegin', `<div class="widget-controls"><span class="small">${safe(widgets[id])}</span><div class="tools">${iconButton('move-widget', `Déplacer ${widgets[id]} avant`, 'arrow-left', `data-widget="${id}" data-step="-1" ${index === 0 ? 'disabled' : ''}`)}${iconButton('move-widget', `Déplacer ${widgets[id]} après`, 'arrow-right', `data-widget="${id}" data-step="1" ${index === layout[view].length - 1 ? 'disabled' : ''}`)}${iconButton('hide-widget', `Masquer ${widgets[id]}`, 'eye-off', `data-widget="${id}" ${layout[view].length === 1 ? 'disabled' : ''}`)}</div><label class="small">Largeur<select data-widget-width="${id}" aria-label="Largeur de ${safe(widgets[id])}">${[['', 'Originale'], [4, 'Tiers'], [6, 'Moitié'], [8, 'Deux tiers'], [12, 'Pleine largeur']].map(([width, label]) => `<option value="${width}" ${String(layout.widths[id] || '') === String(width) ? 'selected' : ''}>${label}</option>`).join('')}</select></label>${variants[id] ? `<label class="small">Présentation<select data-widget-variant="${id}" aria-label="Présentation de ${safe(widgets[id])}">${variants[id].map(([key, label]) => `<option value="${key}" ${key === (layout.variants[id] || variants[id][0][0]) ? 'selected' : ''}>${label}</option>`).join('')}</select></label>` : ''}</div>`);
      grid.append(element);
    }
    if (customizing) grid.insertAdjacentHTML('beforebegin', `<section class="layout-controls" aria-label="Personnalisation du tableau de bord"><div class="row-between"><h2>Modules affichés</h2><div class="tools">${iconButton('reset-layout', 'Rétablir la disposition initiale', 'rotate-ccw')}${iconButton('customize-dashboard', 'Terminer la personnalisation', 'check')}</div></div><div class="layout-options">${availableWidgets[view].map(id => `<label class="check-field"><input type="checkbox" data-widget-toggle="${id}" ${layout[view].includes(id) ? 'checked' : ''} ${layout[view].length === 1 && layout[view][0] === id ? 'disabled' : ''}>${safe(widgets[id])}</label>`).join('')}</div></section>`);
    grid.classList.toggle('is-customizing', customizing); return template.innerHTML;
  }
  let loadError = null;
  try { const stored = localStorage.getItem(storageKey); state = stored ? Finance.validateState(JSON.parse(stored)) : Finance.demo(); } catch (error) { state = Finance.demo(); loadError = error.message; }
  const reference = () => state.mode === 'demo' ? '2026-09-30' : Finance.iso(new Date());
  let period = Finance.range('month', reference());
  const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
  const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
  const money = cents => cents === null ? 'Non couvert' : privacy ? '••••••' : new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(cents === 0 ? 0 : cents / 100);
  const shortDate = value => new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', timeZone: 'UTC' }).format(Finance.date(value));
  const fullDate = value => new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(Finance.date(value));
  const percent = value => new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 1 }).format(value) + ' %';
  const account = id => state.accounts.find(item => item.id === id);
  const context = (granularity = 'day') => ({ ...period, scope, granularity });
  const button = (action, label, glyph = '', primary = false, attributes = '') => `<button type="button" class="button${primary ? ' primary' : ''}" data-action="${action}" ${attributes}>${glyph ? icon(glyph) : ''}${label}</button>`;
  const iconButton = (action, label, glyph, attributes = '') => `<button type="button" class="icon-button" data-action="${action}" aria-label="${safe(label)}" title="${safe(label)}" ${attributes}>${icon(glyph)}</button>`;
  const field = (name, label, value = '', type = 'text', attributes = '') => `<label class="field">${label}<input class="input" name="${name}" type="${type}" value="${safe(value)}" ${attributes}></label>`;
  const selectField = (name, label, choices, value, attributes = '') => `<label class="field">${label}<select name="${name}" ${attributes}>${choices.map(([key, text]) => `<option value="${safe(key)}" ${key === value ? 'selected' : ''}>${safe(text)}</option>`).join('')}</select></label>`;
  const empty = (title, text = '') => `<div class="empty"><h3>${title}</h3>${text ? `<p>${text}</p>` : ''}</div>`;
  function notify(text, error = false) { clearTimeout(noticeTimer); const notice = document.getElementById('notice'); notice.textContent = text; notice.setAttribute('role', error ? 'alert' : 'status'); noticeTimer = setTimeout(() => { notice.textContent = ''; }, error ? 10000 : 4500); }
  function commit(mutator) { if (loadError) throw new Error('Données locales non chargées : restaurer une sauvegarde avant toute modification.'); const next = structuredClone(state); mutator(next); Finance.validateState(next); localStorage.setItem(storageKey, JSON.stringify(next)); state = next; for (const selection of selections.values()) selection.rows = selection.rows.map(row => state.transactions.find(item => item.id === row.id)).filter(Boolean); render(); }
  function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function periodLabel() { return `${shortDate(period.start)} – ${shortDate(period.end)} ${period.end.slice(0, 4)}`; }
  function header(title, action = '', controls = true) {
    if (availableWidgets[view]) action += iconButton('customize-dashboard', 'Personnaliser les modules', 'sliders-horizontal', `aria-pressed="${customizing}"`);
    return `<div class="pagehead"><div><p class="eyebrow">${controls ? periodLabel() : 'Données locales · relevés CSV'}</p><div class="pagehead-left"><h1>${title}</h1>${action}</div></div>${controls ? `<div class="period-controls">${iconButton('previous-period', 'Période précédente', 'chevron-left')}<label class="sr-only" for="period-preset">Période</label><select id="period-preset">${[['month', 'Mois en cours'], ['previous', 'Mois précédent'], ['six', 'Six derniers mois'], ['quarter', 'Trimestre en cours'], ['year', 'Année en cours'], ['custom', 'Dates personnalisées']].map(([key, text]) => `<option value="${key}" ${preset === key ? 'selected' : ''}>${text}</option>`).join('')}</select>${iconButton('next-period', 'Période suivante', 'chevron-right')}${preset === 'custom' ? `<div class="date-range"><label class="sr-only" for="period-start">Du</label><input class="input" id="period-start" type="date" value="${period.start}"><span>–</span><label class="sr-only" for="period-end">Au</label><input class="input" id="period-end" type="date" value="${period.end}"></div>` : ''}</div>` : ''}</div>`;
  }
  function panel(id, title, body, span = 6, action = '', className = '') {
    const selection = selections.get(id);
    const review = id === 'recurring-list' && auxiliary?.type === 'recurring-review' ? `<div class="recurring-review"><span class="small">Les paiements restent dans l’historique.</span>${button('exclude-recurring', 'Écarter de la détection', 'eye-off', false, `data-id="${safe(auxiliary.id)}"`)}</div>` : '';
    return `<section class="module span-${span} component ${className} ${selection ? 'has-detail' : ''}" id="component-${id}"><div class="module-head"><h2>${title}</h2>${action}</div><div class="component-visual">${body}</div>${selection ? `<div class="detail-content"><div class="detail-head"><h3>${safe(selection.title)}</h3>${button('close-detail', 'Retour', 'arrow-left', false, `data-component="${id}"`)}</div>${review}${records(selection.rows, `detail-${id}`)}</div>` : ''}<div class="component-table" id="table-${id}" hidden></div></section>`;
  }
  function metric(title, value, foot, span, tone = '', glyph = '') { return `<section class="module metric span-${span} ${tone}"><div><p class="module-kicker">${title}</p><p class="value money">${value}</p></div><p class="metric-foot">${foot}</p>${glyph ? `<span class="metric-icon">${icon(glyph)}</span>` : ''}</section>`; }
  function meaningfulScale(scale) { return scale === 'auto' || scale === 'day' || Finance.bucket(period.start, scale) !== Finance.bucket(period.end, scale); }
  function grain(id) { if (grains[id] && meaningfulScale(grains[id])) return grains[id]; const count = Finance.days(period.start, period.end).length; return count > 100 ? 'month' : count > 35 ? 'week' : 'day'; }
  function modes(id) { return `<div class="chart-mode" aria-label="Échelle du graphique">${[['auto', 'Auto'], ['day', 'Jour'], ['week', 'Sem.'], ['month', 'Mois'], ['quarter', 'Trim.']].map(([key, label]) => `<button type="button" data-grain="${key}" data-chart="${id}" aria-pressed="${key === (meaningfulScale(grains[id] || 'auto') ? grains[id] || 'auto' : 'auto')}" ${meaningfulScale(key) ? '' : 'disabled title="La période doit contenir au moins deux intervalles"'}>${label}</button>`).join('')}</div>`; }
  function chartNode(id, label, extra = '') { return `<div class="chart ${extra}" id="chart-${id}" tabindex="0" role="img" aria-label="${safe(label)}"></div>`; }
  function chartActions(id, scale = true) { return `${scale ? modes(id) : ''}${iconButton('chart-table', 'Valeurs du graphique', 'table-2', `data-chart="${id}"`)}`; }
  function rowsFor(start = period.start, end = period.end) { return Finance.selectedRows(state, { start, end, scope }).filter(row => row.kind === 'expense' && row.status !== 'pending'); }
  function weekData() {
    const data = Finance.metrics(state, context()), through = [period.end, reference(), data.through || reference()].sort()[0], accounts = Finance.selectedAccounts(state, scope);
    const first = accounts.map(item => item.openingDate).sort().at(-1), base = Finance.bucket(through, 'week');
    if (first) weekOffset = Math.max(-Math.max(0, Math.floor((Finance.date(base) - Finance.date(Finance.bucket(first, 'week'))) / 604800000)), Math.min(0, weekOffset));
    const start = Finance.addDays(base, weekOffset * 7), end = [Finance.addDays(start, 6), through].sort()[0];
    const rows = rowsFor(start, end), previous = rowsFor(Finance.addDays(start, -7), Finance.addDays(end, -7));
    const covered = accounts.length > 0 && accounts.every(item => item.openingDate <= start && item.throughDate >= end);
    const previousCovered = accounts.length > 0 && accounts.every(item => item.openingDate <= Finance.addDays(start, -7) && item.throughDate >= Finance.addDays(end, -7));
    return { start, end, rows, previous, covered, previousCovered, canPrevious: first && start > Finance.bucket(first, 'week'), label: start === Finance.bucket(reference(), 'week') ? 'Dépensé cette semaine' : 'Dépenses de la semaine', total: -rows.reduce((sum, row) => sum + row.amount, 0), previousTotal: -previous.reduce((sum, row) => sum + row.amount, 0) };
  }
  function allocations(items, compact = false) {
    if (layout.variants.envelopes === 'table') return `<div class="table-scroll"><table><thead><tr><th>Enveloppe</th><th class="amount">Dépensé</th><th class="amount">Plafond</th><th class="amount">Disponible</th></tr></thead><tbody>${items.map(item => `<tr><td><button class="button text" data-action="edit-budget" data-category="${safe(item.category)}">${safe(item.category)}</button></td><td class="amount money">${money(item.spent)}</td><td class="amount money">${money(item.limit)}</td><td class="amount money ${item.remaining < 0 ? 'negative' : ''}">${money(item.remaining)}</td></tr>${auxiliary?.type === 'budget' && auxiliary.id === item.category ? `<tr><td colspan="4">${budgetForm(item.category)}</td></tr>` : ''}`).join('')}</tbody></table></div>`;
    if (layout.variants.envelopes === 'rings') return `<div class="envelope-rings">${chartNode('envelope-rings', 'Anneaux de consommation des enveloppes')}<div class="ring-legend">${items.map((item, index) => `<div><button class="allocation-label" data-action="edit-budget" data-category="${safe(item.category)}"><span class="category-dot" style="--color:${palette[index % palette.length]}"></span>${safe(item.category)}</button><p class="money small">${money(item.spent)} / ${money(item.limit)}</p><p class="small ${item.remaining < 0 ? 'negative' : ''}">${item.remaining < 0 ? 'Dépassé de' : 'Reste'} ${money(Math.abs(item.remaining))}</p>${auxiliary?.type === 'budget' && auxiliary.id === item.category ? budgetForm(item.category) : ''}</div>`).join('')}</div></div>`;
    return `<div class="allocations">${items.map((item, index) => `<div><div class="row-between"><button class="allocation-label" data-action="edit-budget" data-category="${safe(item.category)}">${icon(categoryIcons[item.category])}${safe(item.category)}</button><span class="money small">${money(item.spent)} / ${money(item.limit)}</span></div><div class="bar-track" role="meter" aria-label="${safe(item.category)}" aria-valuemin="0" aria-valuemax="${Math.max(item.limit, item.spent, 1)}" aria-valuenow="${item.spent}"><span style="--width:${Math.min(100, item.limit ? item.spent / item.limit * 100 : item.spent ? 100 : 0)}%;--bar:${item.remaining < 0 ? '#d94352' : palette[index % palette.length]}"></span></div><div class="allocation-foot"><span class="${item.remaining < 0 ? 'negative' : ''}">${item.remaining < 0 ? 'Dépassé de' : 'Reste'} ${money(Math.abs(item.remaining))}</span>${compact ? '' : `<span>${money(item.monthly)} / mois</span>`}</div>${auxiliary?.type === 'budget' && auxiliary.id === item.category ? budgetForm(item.category) : ''}</div>`).join('')}</div>`;
  }
  function categoryBody(data, id) { if (!data.categories.length) return empty('Aucune dépense comptabilisée'); return `${layout.variants[id] === 'list' ? '' : `<div class="ring">${chartNode(id, 'Part de chaque catégorie dans les dépenses')}<div class="ring-center"><strong class="money">${money(data.expenses)}</strong><span>Dépenses</span></div></div>`}<div class="category-legend">${data.categories.map((item, index) => `<button data-action="category-detail" data-component="${id}" data-category="${safe(item.name)}"><span><span class="category-dot" style="--color:${palette[index % palette.length]}"></span>${safe(item.name)}</span><strong class="money">${money(item.amount)} <span class="muted">· ${percent(item.amount / Math.max(1, data.expenses) * 100)}</span></strong></button>`).join('')}</div>`; }
  function ringValue(id, label, amount) { const center = document.querySelector(`#component-${id} .ring-center`); if (!center) return; const value = center.querySelector('strong'); value.textContent = money(amount); center.querySelector('span').textContent = label; value.style.fontSize = '22px'; if (value.scrollWidth > value.clientWidth) value.style.fontSize = `${22 * value.clientWidth / value.scrollWidth}px`; }
  function overview() {
    const data = Finance.metrics(state, context()), week = weekData(), budget = Finance.budgetSummary(state, context());
    const unclassified = data.rows.filter(row => row.kind === 'expense' && row.category === 'À classer'), pending = data.rows.filter(row => row.status === 'pending');
    return header("Aujourd'hui") + `<div class="grid">${metric('Solde des comptes', money(data.balance), data.through ? `Solde calculé · relevés au ${shortDate(data.through)}` : 'Solde de départ manquant', 5, 'blue', 'wallet')}${metric(week.label, week.covered ? money(week.total) : 'Non couvert', `${shortDate(week.start)} – ${shortDate(week.end)} · précédent : ${week.previousCovered ? money(week.previousTotal) : 'non couvert'}`, 4, 'coral', 'calendar-days')}${metric('Budget disponible', budget.monthly ? money(budget.remaining) : 'À définir', budget.monthly ? `Plafond de période : ${money(budget.limit)}` : 'Plafond mensuel et enveloppes', 3, 'yellow', 'gauge')}
      ${panel('balance', 'Évolution du solde', `<div class="chart-summary"><span class="legend" style="--legend:#325cf4">Solde calculé</span><span class="badge">${Finance.selectedAccounts(state, scope).length} comptes</span></div>${chartNode('balance', 'Solde cumulé en euros par date')}`, 7, chartActions('balance'))}
      ${panel('week', 'Dépenses de la semaine', `<div class="chart-summary"><span class="legend" style="--legend:#ef6870">${shortDate(week.start)} – ${shortDate(week.end)}</span><span class="legend" style="--legend:#b7c7ff">Semaine précédente</span></div>${chartNode('week', 'Dépenses quotidiennes de la semaine et comparaison précédente')}`, 5, `<div class="tools">${iconButton('previous-week', 'Semaine précédente', 'chevron-left', week.canPrevious ? '' : 'disabled')}${iconButton('next-week', 'Semaine suivante', 'chevron-right', weekOffset === 0 ? 'disabled' : '')}${chartActions('week', false)}</div>`)}
      ${panel('categories', 'Dépenses par catégorie', categoryBody(data, 'categories'), 4, chartActions('categories', false))}
      ${panel('envelopes', 'Enveloppes', `<div class="row-between" style="margin-bottom:20px"><span class="small">Disponible par catégorie</span><a href="#budget" class="button text">Budget${icon('arrow-up-right')}</a></div>${budget.envelopes.length ? allocations(budget.envelopes.slice(0, 5), true) : empty('Aucune enveloppe définie')}`, 5)}
      ${panel('quality', 'Qualité des relevés', `<p class="quality-number">${data.rows.length}</p><p class="module-kicker">opérations dans la période</p><div class="quality-row">${icon('calendar-check')}<div><strong>${data.through ? shortDate(data.through) : '—'}</strong><small>Dernière date couverte par tous les comptes affichés</small></div></div><div class="quality-row">${icon('circle-help')}<div><button class="button text" data-action="unclassified-detail">${unclassified.length} à classer</button><small>${money(-unclassified.reduce((sum, row) => sum + row.amount, 0))} de dépenses</small></div></div><div class="quality-row">${icon('clock-3')}<div><strong>${pending.length} en attente</strong><small>Non incluses dans les totaux comptabilisés</small></div></div><a class="link-row" href="#import">Importer le prochain CSV${icon('arrow-up-right')}</a>`, 3)}
      <section class="module table-module span-12"><div class="module-head"><h2>Dernières opérations</h2><a class="button text" href="#history">Historique${icon('arrow-up-right')}</a></div>${records([...data.rows].sort((first, second) => second.date.localeCompare(first.date)).slice(0, 6), 'recent')}</section></div>`;
  }
  function editorForm(row) {
    const owner = account(row.account)?.owner, automatic = row.splitMode === 'auto' || row.splitMode === undefined && row.splitA === state.household.ratio;
    const allocation = !row.shared && owner !== 'joint' ? 'personal' : automatic ? 'auto' : row.splitA === 100 ? 'a' : row.splitA === 0 ? 'b' : 'custom';
    return `<form class="inline-editor transaction-editor" data-form="transaction" data-id="${safe(row.id)}"><div class="editor-heading"><div><h3>${safe(row.merchant)}</h3><p class="source-note">${fullDate(row.date)} · ${safe(account(row.account)?.name)} · <span class="money">${money(row.amount)}</span></p></div>${iconButton('cancel-edit', 'Fermer les détails', 'x')}</div>
      ${pendingAction ? `<div class="inline-warning">Modifications non enregistrées.<div class="tools">${button('keep-edit', 'Continuer l’édition', 'pencil')}${button('discard-edit', 'Abandonner', 'x')}</div></div>` : ''}
      <div class="transaction-fields">${field('merchant', 'Marchand', row.merchant, 'text', 'required')}${selectField('category', 'Catégorie', Finance.categories.map(name => [name, name]), row.category)}${selectField('allocation', 'Répartition', [['personal', 'Personnel · titulaire'], ['auto', 'Commun · selon les revenus'], ['a', `100 % ${state.household.a}`], ['b', `100 % ${state.household.b}`], ['custom', 'Pourcentage personnalisé']], allocation)}<div class="custom-split" ${allocation !== 'custom' ? 'hidden' : ''}>${field('splitA', `Part de ${safe(state.household.a)} (%)`, row.splitA, 'number', 'min="0" max="100" step="0.1"')}</div><label class="field transaction-note">Note<textarea name="note" rows="1">${safe(row.note)}</textarea></label></div>
      <details class="transaction-extra"><summary>Nature et récurrence</summary><div class="transaction-fields">${selectField('kind', 'Nature du mouvement', [['expense', 'Dépense'], ['income', 'Revenu'], ['transfer', 'Transfert entre comptes'], ['settlement', 'Règlement entre personnes']], row.kind)}${selectField('recurrence', 'Récurrence', [['auto', 'Détection automatique'], ['include', 'Considérer comme récurrent'], ['exclude', 'Exclure de la détection']], row.recurrence || 'auto')}<div class="recurrence-frequency" ${row.recurrence !== 'include' ? 'hidden' : ''}>${selectField('recurrenceFrequency', 'Fréquence', [['monthly', 'Mensuelle'], ['weekly', 'Hebdomadaire'], ['yearly', 'Annuelle']], row.recurrenceFrequency || 'monthly')}</div></div><p class="source-note">Libellé bancaire : ${safe(row.bankLabel)}</p></details>
      <div class="editor-footer"><p class="error" role="alert"></p><div class="tools">${button('cancel-edit', 'Annuler')}<button class="button primary" type="submit">${icon('check')}Enregistrer</button></div></div></form>`;
  }
  function records(rows, host, split = false) {
    if (!rows.length) return empty('Aucune opération dans ce périmètre');
    const shared = split ? Finance.sharing(state, context()).allocations : [];
    const details = row => editor?.id === row.id && editor.host === host ? editorForm(row) : '';
    const link = row => `<button class="record-link" data-action="edit-transaction" data-id="${safe(row.id)}" data-host="${host}" aria-expanded="${editor?.id === row.id && editor.host === host}"><span class="merchant-mark">${icon(categoryIcons[row.category] || 'circle-help')}</span><span class="record-name">${safe(row.merchant)}</span></button>`;
    const desktop = `<div class="desktop-table table-scroll"><table><thead><tr><th>Opération</th><th>Date</th><th>${split ? 'Payé par' : 'Catégorie'}</th><th class="amount">Montant CSV</th>${split ? `<th class="amount">${safe(state.household.a)}</th><th class="amount">${safe(state.household.b)}</th><th>Répartition</th>` : '<th>Compte / statut</th>'}</tr></thead><tbody>${rows.map(row => { const allocation = shared.find(item => item.row.id === row.id); return `<tr><td>${link(row)}</td><td>${shortDate(row.date)}</td><td>${safe(split ? account(row.account)?.owner === 'joint' ? 'Commun' : state.household[account(row.account)?.owner] : row.category)}</td><td class="amount money ${row.amount < 0 ? 'negative' : 'positive'}">${money(row.amount)}</td>${split ? `<td class="amount money">${money(allocation?.partA ?? 0)}</td><td class="amount money">${money(allocation?.partB ?? 0)}</td><td><span class="badge ${row.shared ? 'blue' : ''}">${!row.shared && account(row.account)?.owner !== 'joint' ? 'Personnel' : allocation?.automatic ? 'Selon revenus' : percent(allocation?.ratio || 0)}</span></td>` : `<td><span class="small">${safe(account(row.account)?.name)}</span>${row.status === 'pending' ? '<span class="badge warn">En attente</span>' : row.kind === 'transfer' ? '<span class="badge blue">Transfert</span>' : ''}</td>`}</tr>${details(row) ? `<tr class="expanded-record"><td colspan="${split ? 7 : 5}">${details(row)}</td></tr>` : ''}`; }).join('')}</tbody></table></div>`;
    return `<div class="records" data-records="${host}">${desktop}<div class="mobile-list">${rows.map(row => `<div class="mobile-record"><div>${link(row)}<p class="source-note">${shortDate(row.date)} · ${safe(row.category)} · ${safe(account(row.account)?.name)}</p>${split ? `<p class="source-note">${safe(state.household.a)} ${money(shared.find(item => item.row.id === row.id)?.partA || 0)} · ${safe(state.household.b)} ${money(shared.find(item => item.row.id === row.id)?.partB || 0)}</p>` : ''}</div><span class="money ${row.amount < 0 ? 'negative' : 'positive'}">${money(row.amount)}</span></div>${details(row)}`).join('')}</div></div>`;
  }
  function filteredRows() { return Finance.selectedRows(state, context()).filter(row => `${row.merchant} ${row.bankLabel} ${row.category} ${account(row.account)?.name}`.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')) && (!categoryFilter || row.category === categoryFilter) && (historyType === 'all' || historyType === 'expense' && row.kind === 'expense' || historyType === 'income' && row.kind === 'income' || historyType === 'pending' && row.status === 'pending')).sort((first, second) => second.date.localeCompare(first.date)); }
  function historyView() {
    const rows = filteredRows(), size = 12; pageIndex = Math.min(pageIndex, Math.max(0, Math.ceil(rows.length / size) - 1));
    return header('Historique', iconButton('export-csv', 'Exporter les opérations affichées', 'download')) + `<section class="module table-module"><div class="toolbar"><label class="search">${icon('search')}<span class="sr-only">Recherche</span><input class="input" id="search" value="${safe(query)}" placeholder="Marchand, catégorie, compte…"></label><label class="sr-only" for="category-filter">Catégorie</label><select id="category-filter"><option value="">Toutes les catégories</option>${Finance.categories.map(name => `<option ${name === categoryFilter ? 'selected' : ''}>${safe(name)}</option>`).join('')}</select><div class="filters">${[['all', 'Tout'], ['expense', 'Dépenses'], ['income', 'Revenus'], ['pending', 'En attente']].map(([key, label]) => `<button data-history-type="${key}" aria-pressed="${historyType === key}">${label}</button>`).join('')}</div></div>${records(rows.slice(pageIndex * size, (pageIndex + 1) * size), 'history')}<div class="table-footer"><span>${rows.length} opérations · <span class="money">${money(rows.reduce((sum, row) => sum + row.amount, 0))}</span></span><div class="tools">${iconButton('previous-page', 'Page précédente', 'chevron-left', pageIndex === 0 ? 'disabled' : '')}<span>${pageIndex + 1} / ${Math.max(1, Math.ceil(rows.length / size))}</span>${iconButton('next-page', 'Page suivante', 'chevron-right', (pageIndex + 1) * size >= rows.length ? 'disabled' : '')}</div></div></section>`;
  }
  function formFooter() { return `<div class="editor-footer"><p class="error" role="alert"></p><div class="tools">${button('close-auxiliary', 'Annuler')}<button type="submit" class="button primary">${icon('check')}Enregistrer</button></div></div>`; }
  function budgetForm(category = '') { return `<div class="inline-panel"><form data-form="budget" data-id="${safe(category)}"><div class="form-grid">${selectField('category', 'Enveloppe', Finance.categories.filter(name => name !== 'Revenus').map(name => [name, name]), category || 'Alimentation')}${field('amount', 'Plafond mensuel (€)', state.budgets[category] === undefined ? '' : (state.budgets[category] / 100).toFixed(2), 'text', 'inputmode="decimal" required')}</div>${category ? button('remove-budget', 'Retirer l’enveloppe', 'trash-2', false, `data-category="${safe(category)}"`) : ''}${formFooter()}</form></div>`; }
  function budgetView() {
    const data = Finance.budgetSummary(state, context());
    return header('Budget') + `<div class="grid">${metric('Plafond mensuel global', data.monthly ? money(data.monthly) : 'À définir', state.monthlyBudget === undefined ? 'Somme des enveloppes · modifiable indépendamment' : 'Toutes les dépenses, enveloppées ou non', 4, 'blue')}${metric('Dépensé sur la période', money(data.spent), periodLabel(), 4, 'coral')}${metric('Disponible sur la période', data.monthly ? money(data.remaining) : 'Non défini', data.monthly ? `Plafond proratisé : ${money(data.limit)}` : 'Aucun plafond mensuel défini', 4, 'yellow')}
      ${panel('budget-envelopes', 'Enveloppes mensuelles', `${auxiliary?.type === 'overall' ? `<div class="inline-panel"><form data-form="overall">${field('amount', 'Budget global mensuel (€)', (data.monthly / 100).toFixed(2), 'text', 'inputmode="decimal" required')}${formFooter()}</form></div>` : button('edit-overall', 'Budget global', 'sliders-horizontal')}${data.envelopes.length ? `<div style="margin-top:20px">${allocations(data.envelopes)}</div>` : empty('Aucune enveloppe définie')}${auxiliary?.type === 'budget' && (!auxiliary.id || !Object.hasOwn(state.budgets, auxiliary.id)) ? budgetForm(auxiliary.id || '') : ''}`, 7, `${envelopeActions()}${iconButton('new-budget', 'Définir une enveloppe mensuelle', 'plus')}`)}
      ${panel('budget-pace', 'Dépenses cumulées vs plafond', data.monthly ? `<div class="chart-summary"><span class="legend" style="--legend:#ef6870">Dépenses observées cumulées</span><span class="legend" style="--legend:#325cf4">Plafond proratisé à cette date</span></div>${chartNode('budget-pace', 'Dépenses cumulées comparées au budget proratisé')}<p class="source-note">${periodLabel()} · budget mensuel ${money(data.monthly)}</p>` : empty('Définir le plafond avant de comparer'), 5, chartActions('budget-pace'))}
      ${panel('outside', 'Dépenses sans enveloppe', Finance.metrics(state, context()).categories.filter(item => !Object.hasOwn(state.budgets, item.name)).map(item => `<div class="statline"><button class="button text" data-action="edit-budget" data-category="${safe(item.name)}">${safe(item.name)}${icon('plus')}</button><strong class="money">${money(item.amount)}</strong></div>`).join('') || empty('Chaque catégorie dépensée a une enveloppe'), 12)}</div>`;
  }
  function analyticsView() {
    const data = Finance.metrics(state, context()), days = Finance.days(period.start, period.end).slice(-42), totals = new Map();
    for (const row of rowsFor()) totals.set(row.date, (totals.get(row.date) || 0) - row.amount);
    const maximum = Math.max(1, ...totals.values()), months = Finance.metrics(state, context('month')).series;
    return header('Analyse') + `<div class="grid">${metric('Revenus importés', money(data.income), 'Hors transferts et mouvements en attente', 4, 'blue')}${metric('Dépenses importées', money(data.expenses), `${rowsFor().length} paiements comptabilisés`, 4, 'coral')}${metric('Revenus − dépenses', money(data.net), 'Différence des flux · pas un solde ni une épargne certifiée', 4, 'yellow')}
      ${panel('expenses', 'Dépenses dans le temps', chartNode('expenses', 'Dépenses par intervalle avec dates et montants'), 8, chartActions('expenses'))}
      ${panel('analysis-categories', 'Dépenses par catégorie', categoryBody(data, 'analysis-categories'), 4, chartActions('analysis-categories', false))}
      ${panel('days', 'Dépenses par jour', `<div class="heat-grid">${days.map(value => `<button class="heat-day" data-action="day-detail" data-day="${value}" style="--heat:color-mix(in srgb,#9db5ff ${totals.get(value) ? 15 + (totals.get(value) / maximum) * 60 : 0}%,white)" title="${fullDate(value)} : ${safe(money(totals.get(value) || 0))}"><span>${shortDate(value)}</span><small>${money(totals.get(value) || 0)}</small></button>`).join('')}</div><p class="source-note">${days.length} derniers jours de la période · paiements comptabilisés</p>`, 6)}
      ${panel('merchants', 'Dépenses par marchand', chartNode('merchants', 'Dépenses par marchand avec montants en euros'), 6, chartActions('merchants', false))}
      ${panel('monthly', 'Bilan mensuel', `<div class="table-scroll"><table><thead><tr><th>Mois</th><th class="amount">Revenus</th><th class="amount">Dépenses</th><th class="amount">Différence</th></tr></thead><tbody>${months.map(item => `<tr><td>${new Intl.DateTimeFormat('fr-FR', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(Finance.date(item.date))}</td><td class="amount money">${money(item.income)}</td><td class="amount money">${money(item.expenses)}</td><td class="amount money">${money(item.income - item.expenses)}</td></tr>`).join('')}</tbody></table></div>`, 12)}</div>`;
  }
  function sharingView() {
    const data = Finance.sharing(state, context()), totalA = data.allocations.reduce((sum, item) => sum + item.partA, 0), totalB = data.allocations.reduce((sum, item) => sum + item.partB, 0);
    const household = Finance.sharing(state, { ...context(), scope: 'all' }), amount = household.owedToA;
    return header('Partage') + `<div class="grid">
      ${panel('reimbursement', 'Remboursement du foyer', `<div class="reimbursement"><div><p class="module-kicker">${amount === 0 ? 'Dépenses équilibrées' : `${safe(amount > 0 ? state.household.b : state.household.a)} doit envoyer à ${safe(amount > 0 ? state.household.a : state.household.b)}`}</p><p class="value money">${money(Math.abs(amount))}</p></div><span class="badge ${household.rule.source === 'income' ? 'blue' : 'warn'}">${household.rule.source === 'income' ? 'Selon les revenus CSV' : 'Répartition provisoire'}</span></div><p class="source-note">Tous les comptes du foyer · dépenses comptabilisées des comptes personnels après répartition · règlements importés déduits. Les dépenses du compte commun ne demandent pas de remboursement entre personnes.</p>`, 12)}
      ${panel('person-a', safe(state.household.a), `<p class="module-kicker">Part des dépenses affichées</p><p class="value money">${money(totalA)}</p><div class="statline"><span class="small">Revenus CSV</span><strong class="money">${money(data.rule.incomeA)}</strong></div><div class="statline"><span class="small">Payé depuis les comptes personnels</span><strong class="money">${money(data.paidA)}</strong></div>`, 4)}
      ${panel('person-b', safe(state.household.b), `<p class="module-kicker">Part des dépenses affichées</p><p class="value money">${money(totalB)}</p><div class="statline"><span class="small">Revenus CSV</span><strong class="money">${money(data.rule.incomeB)}</strong></div><div class="statline"><span class="small">Payé depuis les comptes personnels</span><strong class="money">${money(data.paidB)}</strong></div>`, 4)}
      ${panel('ratio', 'Répartition commune', `<p class="subvalue">${percent(data.rule.ratio)} / ${percent(100 - data.rule.ratio)}</p><div class="ratio-track"><span style="width:${data.rule.ratio}%"></span><span style="width:${100 - data.rule.ratio}%"></span></div><div class="row-between small"><span>${safe(state.household.a)}</span><span>${safe(state.household.b)}</span></div><p class="source-note">${data.rule.source === 'income' ? 'Proportion des revenus importés' : 'Revenus incomplets ou absents : répartition provisoire du foyer.'}</p><div class="statline"><span class="small">Débits du compte commun</span><strong class="money">${money(data.paidJoint)}</strong></div>`, 4)}
      <section class="module table-module span-12"><div class="module-head"><h2>Répartition des transactions</h2><span class="badge">${data.rows.length} dépenses</span></div>${records([...data.rows].sort((first, second) => second.date.localeCompare(first.date)), 'sharing', true)}</section></div>`;
  }
  function detected() { return Finance.detectRecurring(state, period.end < reference() ? period.end : reference(), scope); }
  function recurringView() {
    const items = detected(), excluded = [...new Map(state.transactions.filter(row => row.recurrence === 'exclude' && (scope === 'all' || row.account === scope)).map(row => [`${row.account}:${row.merchant}`, row])).values()];
    return header('Récurrents détectés') + `<div class="grid">${metric('Charges régulières repérées', String(items.length), 'Selon les répétitions observées dans les CSV', 4, 'blue')}${metric('Équivalent mensuel estimé', money(items.reduce((sum, item) => sum + item.monthly, 0)), 'Moyenne des paiements · fréquences hebdomadaires et annuelles converties', 4, 'coral')}${metric('Historique disponible', String(state.transactions.filter(row => row.kind === 'expense').length) + ' débits', `Détection jusqu’au ${shortDate(period.end < reference() ? period.end : reference())}`, 4, 'yellow')}${panel('recurring-list', 'Abonnements et charges observés', items.length ? items.map((item, index) => `<div class="recurring-row"><span class="merchant-mark">${icon(categoryIcons[item.category] || 'repeat-2')}</span><div class="row-copy"><button class="button text" data-action="recurring-detail" data-index="${index}">${safe(item.name)}</button><small>${safe(account(item.account)?.name)} · ${item.rows.length} débits · ${item.confidence === 'candidate' ? 'à vérifier' : item.confidence === 'reviewed' ? 'défini par toi' : 'répétition observée'}</small></div><div class="recurring-cost money">${money(item.average)}<small>${{ monthly: '/ mois', weekly: '/ semaine', yearly: '/ an' }[item.frequency]}</small></div>${iconButton('recurring-detail', `Revoir ${item.name}`, 'ellipsis', `data-index="${index}"`)}</div>`).join('') : empty('Pas encore de répétition identifiable', 'Deux relevés ou une annotation de transaction permettent de vérifier une récurrence.'), 7)}${panel('recurring-dates', 'Prochaines dates estimées', items.slice().sort((first, second) => first.nextDate.localeCompare(second.nextDate)).slice(0, 7).map(item => `<div class="statline"><div><h3>${safe(item.name)}</h3><p class="source-note">${shortDate(item.nextDate)} ${item.nextDate < period.end ? '· non retrouvé dans les CSV récents' : '· estimation'}</p></div><strong class="money">${money(item.amount)}</strong></div>`).join('') || empty('Aucune échéance estimable'), 5)}${panel('recurring-history', 'Paiements récurrents observés', chartNode('recurring-history', 'Somme des débits récurrents observés par intervalle'), 12, chartActions('recurring-history'))}${excluded.length ? panel('excluded', 'Écartés de la détection', excluded.map(row => `<div class="statline"><span>${safe(row.merchant)} · ${safe(account(row.account)?.name)}</span>${button('reconsider-recurring', 'Rétablir le suivi', 'rotate-ccw', false, `data-id="${safe(row.id)}"`)}</div>`).join(''), 12) : ''}</div>`;
  }
  function accountForm(item) { return `<div class="inline-panel"><form data-form="account" data-id="${safe(item.id)}"><div class="form-grid">${field('name', 'Nom du compte', item.name, 'text', 'required')}${selectField('owner', 'Titulaire', [['a', state.household.a], ['b', state.household.b], ['joint', 'Compte commun']], item.owner)}${field('openingDate', 'Solde avant les opérations du', item.openingDate, 'date', 'required')}${field('opening', 'Solde de départ (€)', (item.opening / 100).toFixed(2), 'text', 'inputmode="decimal" required')}</div>${formFooter()}</form></div>`; }
  function accountsView() {
    return header('Comptes', `<a class="icon-button" href="#import" title="Importer un compte depuis un CSV" aria-label="Importer un compte depuis un CSV">${icon('file-up')}</a>`) + `<div class="grid">${panel('account-list', 'Comptes issus des relevés', state.accounts.map(item => `<div class="account-row"><span class="account-glyph">${icon(item.owner === 'joint' ? 'users' : 'wallet')}</span><div class="row-copy"><h3>${safe(item.name)}</h3><small>${item.owner === 'joint' ? 'Commun' : safe(state.household[item.owner])} · ${state.transactions.filter(row => row.account === item.id).length} opérations CSV</small></div><div class="account-value"><strong class="money">${money(Finance.balance(state, item.id, period.end < item.throughDate ? period.end : item.throughDate))}</strong><small>Couverture au ${shortDate(item.throughDate)}</small></div>${iconButton('edit-account', `Point de départ de ${item.name}`, 'pencil', `data-id="${safe(item.id)}"`)}</div>${auxiliary?.type === 'account' && auxiliary.id === item.id ? accountForm(item) : ''}`).join('') || empty('Aucun compte importé'), 8)}${panel('anchors', 'Points de départ', state.accounts.map(item => `<div class="statline"><div><h3>${safe(item.name)}</h3><p class="source-note">Avant les opérations du ${shortDate(item.openingDate)}</p></div><strong class="money">${money(item.opening)}</strong></div>`).join('') || '<a class="button primary" href="#import">Importer le premier CSV</a>', 4)}${panel('accounts', 'Évolution de chaque compte', chartNode('accounts', 'Soldes cumulés par compte depuis les points de départ'), 12, chartActions('accounts'))}</div>`;
  }
  function householdForm(personal = false) { return `<div class="inline-panel"><form data-form="${personal ? 'personal' : 'household'}"><div class="form-grid">${field('a', 'Première personne', personal ? '' : state.household.a, 'text', 'required')}${field('b', 'Deuxième personne', personal ? '' : state.household.b, 'text', 'required')}${field('ratio', 'Part provisoire sans revenus CSV (%)', personal ? 50 : state.household.ratio, 'number', 'min="0" max="100" required')}</div>${personal ? '<p class="source-note">Seules les données d’exemple de cet espace seront remplacées.</p>' : ''}${formFooter()}</form></div>`; }
  function settingsView() { return header('Foyer et sauvegardes', '', false) + `<div class="grid">${panel('household', 'Le foyer', `<div class="setting-row"><div><h3>${safe(state.household.a)} & ${safe(state.household.b)}</h3><p>Répartition commune calculée depuis les revenus CSV</p></div>${button('edit-household', 'Modifier', 'pencil')}</div>${auxiliary?.type === 'household' ? householdForm() : ''}${state.mode === 'demo' ? `<div class="setting-row"><div><h3>Passer à mes relevés</h3><p>Données d’exemple clairement séparées des données personnelles</p></div>${button('start-personal', 'Mon foyer', 'file-up')}</div>${auxiliary?.type === 'personal' ? householdForm(true) : ''}` : ''}`, 6)}${panel('backups', 'Sauvegardes', `<div class="setting-row"><div><h3>Exporter toutes les données</h3><p>CSV conservés, annotations, comptes et budgets</p></div>${button('backup', 'Exporter', 'download')}</div><div class="setting-row"><div><h3>Restaurer un fichier JSON</h3><p>Vérification avant remplacement</p></div>${button('restore', 'Restaurer', 'upload')}</div>${restoreCandidate ? `<div class="notice-inline">${restoreCandidate.accounts.length} comptes · ${restoreCandidate.transactions.length} opérations. Les données actuelles seront remplacées.<div class="tools">${button('backup', 'Sauvegarder avant', 'download')}${button('confirm-restore', 'Confirmer la restauration', 'check', true)}${button('cancel-restore', 'Annuler')}</div></div>` : ''}`, 6)}${panel('local', 'Source des données', '<p class="small">Relevés CSV locaux. Aucune connexion bancaire, aucun paiement, aucune résiliation ni opération créée par l’application. Les annotations ne modifient pas le montant ou le libellé bancaire d’origine.</p><a class="button text" href="#import">Importer un relevé</a>', 12)}</div>`; }
  function importView() {
    const draft = importDraft, choices = [['new', 'Compte issu de ce CSV'], ...state.accounts.map(item => [item.id, item.name])], mappings = [['date', 'Date'], ['merchant', 'Libellé'], ['amount', 'Montant signé'], ['debit', 'Débit'], ['credit', 'Crédit'], ['direction', 'Sens'], ['category', 'Catégorie'], ['status', 'Statut']];
    return header('Importer un CSV', '', false) + `<div class="grid">${panel('csv', 'Le relevé', `${state.mode === 'demo' ? `<div class="notice-inline">Espace d’exemple. ${button('start-personal', 'Passer à mon foyer', 'file-up')}${auxiliary?.type === 'personal' ? householdForm(true) : ''}</div>` : ''}<div class="import-layout"><div class="file-zone"><label for="csv-file">Fichier CSV</label><input id="csv-file" type="file" accept=".csv,text/csv"><span class="small">${safe(draft?.name || 'Aucun fichier sélectionné')}</span></div>${selectField('importAccount', 'Associer le relevé', choices, draft?.account || 'new', 'id="import-account"')}${field('closing', 'Solde de contrôle (€), facultatif', draft?.closingText || '', 'text', 'id="closing-balance" inputmode="decimal"')}</div>${draft ? `${draft.account === 'new' ? `<div class="import-new"><h3>Compte identifié par ce relevé</h3><div class="form-grid" style="margin-top:16px">${field('accountName', 'Nom', draft.accountName, 'text', 'id="new-account-name" required')}${selectField('accountOwner', 'Titulaire', [['a', state.household.a], ['b', state.household.b], ['joint', 'Compte commun']], draft.owner, 'id="new-account-owner"')}${field('openingDate', 'Solde avant les opérations du', draft.openingDate, 'date', 'id="new-opening-date" required')}${field('opening', 'Solde de départ (€)', draft.openingText, 'text', 'id="new-opening" inputmode="decimal" required')}</div></div>` : ''}<div class="mapping">${mappings.map(([key, text]) => selectField(key, text, [['', '—'], ...draft.fields.map(name => [name, name])], draft.mapping[key], `data-mapping="${key}"`)).join('')}${field('closingDate', 'Dernière date du relevé', draft.closingDate, 'date', 'id="closing-date" required')}</div><div class="setting-row"><label class="check-field"><input type="checkbox" id="include-duplicates" ${draft.includeDuplicates ? 'checked' : ''}>Inclure les doublons potentiels après revue</label>${button('check-import', 'Contrôler', 'scan-line', true)}</div>` : ''}`, 12)}${draft?.review ? importReview() : ''}</div>`;
  }
  function importReview() {
    const review = importDraft.review;
    return panel('csv-review', 'Avant import', `<div class="chart-summary"><div><span class="module-kicker">Nouvelles lignes</span><strong>${review.rows.length}</strong></div><div><span class="module-kicker">Doublons exclus</span><strong>${review.duplicates}</strong></div><div><span class="module-kicker">Erreurs</span><strong>${review.errors.length}</strong></div></div>${review.errors.length ? `<div class="notice-inline error">${review.errors.slice(0, 6).map(error => `Ligne ${error.line} : ${safe(error.message)}`).join('<br>')}</div>` : ''}${review.control ? `<div class="statline"><span>Solde calculé depuis l’ouverture</span><strong class="money">${money(review.control.expected)}</strong></div><div class="statline"><span>Solde observé</span><strong class="money">${money(review.control.observed)}</strong></div><div class="statline"><span>Écart${review.control.difference ? ' · import bloqué' : ''}</span><strong class="money ${review.control.difference ? 'negative' : ''}">${money(review.control.difference)}</strong></div>` : '<div class="notice-inline">Pas de solde bancaire de contrôle : solde calculé, non rapproché avec une observation bancaire.</div>'}<p class="source-note">${review.account ? `Nouveau compte : ${safe(review.account.name)} · ouverture ${money(review.account.opening)}` : safe(account(importDraft.account)?.name)}</p><div class="table-scroll"><table><thead><tr><th>Date</th><th>Libellé CSV</th><th class="amount">Montant</th></tr></thead><tbody>${review.rows.slice(0, 8).map(row => `<tr><td>${shortDate(row.date)}</td><td>${safe(row.bankLabel)}</td><td class="amount money">${money(row.amount)}</td></tr>`).join('')}</tbody></table></div><div class="tools" style="margin-top:20px">${button('commit-import', `Importer ${review.rows.length} opérations${review.account ? ' et le compte' : ''}`, 'check', true, review.errors.length || !review.rows.length || review.control?.difference || state.mode === 'demo' ? 'disabled' : '')}</div>`, 12);
  }
  function captureForms() { for (const form of main.querySelectorAll('form[data-form]')) { if (!form.getClientRects().length || form.dataset.form === 'transaction' && !editor || form.dataset.form !== 'transaction' && !auxiliary) continue; const entries = [...new FormData(form).entries()]; if (form.querySelector('.transaction-extra')) entries.push(['$expanded', String(form.querySelector('.transaction-extra').open)]); drafts.set(`${form.dataset.form}:${form.dataset.id || ''}`, entries); } }
  function restoreForms() { for (const form of main.querySelectorAll('form[data-form]')) { const entries = drafts.get(`${form.dataset.form}:${form.dataset.id || ''}`); if (!entries) continue; for (const element of form.elements) { if (!element.name) continue; const saved = entries.find(([name]) => name === element.name); if (saved) element.value = saved[1]; } const custom = form.querySelector('.custom-split'); if (custom) custom.hidden = form.elements.allocation.value !== 'custom'; const frequency = form.querySelector('.recurrence-frequency'); if (frequency) frequency.hidden = form.elements.recurrence.value !== 'include'; const extra = form.querySelector('.transaction-extra'); if (extra) extra.open = entries.find(([name]) => name === '$expanded')?.[1] === 'true'; } }
  function render() {
    captureForms(); const focus = main.contains(document.activeElement) ? { id: document.activeElement.id, data: { ...document.activeElement.dataset }, name: document.activeElement.name, form: document.activeElement.closest('form')?.dataset.form } : null;
    const oldCharts = new Map([...chartRegistry].map(([id, instance]) => [id, instance.getDom()]));
    const views = { today: overview, history: historyView, budget: budgetView, analytics: analyticsView, sharing: sharingView, recurring: recurringView, accounts: accountsView, import: importView, settings: settingsView };
    main.innerHTML = arrangeModules(views[view]());
    if (view === 'import') { const input = main.querySelector('#csv-file'); input.accept = '.csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'; input.previousElementSibling.textContent = 'CSV ou Excel'; main.querySelector('h1').textContent = 'Importer un relevé'; const accountHeading = main.querySelector('.import-new h3'); if (accountHeading) accountHeading.textContent = 'Compte identifié dans le relevé'; }
    if (view === 'import' && importDraft?.sources.length > 1) main.querySelector('.import-layout').insertAdjacentHTML('afterbegin', selectField('sourceAccount', 'Compte source', importDraft.sources.map(name => [name, name]), importDraft.sourceKey, 'id="source-account"'));
    for (const [id, element] of oldCharts) { const placeholder = document.getElementById(`chart-${id}`); if (placeholder) placeholder.replaceWith(element); else { chartRegistry.get(id).dispose(); chartRegistry.delete(id); } }
    document.getElementById('data-label').textContent = state.mode === 'demo' ? 'Exemple' : 'Local';
    const scopeSelect = document.getElementById('scope'); scopeSelect.innerHTML = `<option value="all">Foyer · tous les comptes</option>${state.accounts.map(item => `<option value="${safe(item.id)}">${safe(item.name)}</option>`).join('')}`; scopeSelect.value = scope;
    document.getElementById('dock').innerHTML = Object.entries(routes).slice(0, 6).map(([key, [title, glyph]]) => `<a class="dock-link ${['sharing', 'recurring'].includes(key) ? 'secondary' : ''}" href="#${key}" ${view === key ? 'aria-current="page"' : ''}>${icon(glyph)}<span>${title}</span></a>`).join('');
    restoreForms(); window.lucide.createIcons({ attrs: { 'aria-hidden': 'true' } }); drawCharts();
    if (focus) { const replacement = focus.id ? document.getElementById(focus.id) : focus.name ? [...main.querySelectorAll('[name]')].find(element => element.name === focus.name && element.closest('form')?.dataset.form === focus.form && element.getClientRects().length) : [...main.querySelectorAll('button,a')].find(element => Object.keys(focus.data).length && Object.entries(focus.data).every(([key, value]) => element.dataset[key] === value) && element.getClientRects().length); replacement?.focus({ preventScroll: true }); }
  }
  const tooltip = { trigger: 'axis', confine: true, transitionDuration: 0, backgroundColor: '#fff', borderColor: '#d8deef', padding: [12, 16], textStyle: { color: '#202332', fontFamily: 'DM Sans', fontSize: 12 }, axisPointer: { type: 'line', lineStyle: { color: '#697fae', type: 'dashed', width: 1 }, label: { show: true, backgroundColor: '#325cf4' } }, position: (point, parameters, dom, rect, size) => [Math.max(8, Math.min(point[0] - size.contentSize[0] / 2, size.viewSize[0] - size.contentSize[0] - 8)), Math.max(8, point[1] - size.contentSize[1] - 18)], formatter: parameters => { const items = Array.isArray(parameters) ? parameters : [parameters]; return `<strong>${safe(items[0].axisValueLabel || items[0].name)}</strong>${items.map(item => `<div style="display:flex;justify-content:space-between;gap:20px;margin-top:6px"><span>${item.marker || ''}${safe(item.seriesName)}</span><strong>${item.value === null ? 'Non couvert' : money(Math.round(Number(item.value) * 100))}</strong></div>`).join('')}`; } };
  function axes(labels) { return { tooltip, grid: { top: 20, left: 12, right: 18, bottom: 8, containLabel: true }, xAxis: { type: 'category', data: labels, axisTick: { show: false }, axisLine: { lineStyle: { color: '#e0e5f1' } }, axisLabel: { hideOverlap: true, color: '#626779', fontSize: 10 } }, yAxis: { type: 'value', name: privacy ? '' : '€', nameTextStyle: { color: '#626779', fontSize: 10 }, splitLine: { lineStyle: { color: '#eceff7', type: 'dashed' } }, axisLabel: { color: '#626779', fontSize: 10, formatter: value => privacy ? '•••' : new Intl.NumberFormat('fr-FR', { notation: 'compact', maximumFractionDigits: 1 }).format(value) } } }; }
  function bucketLabel(item, scale) { if (scale === 'month') return new Intl.DateTimeFormat('fr-FR', { month: 'short', year: '2-digit', timeZone: 'UTC' }).format(Finance.date(item.date)); if (scale === 'quarter') return `T${Math.floor(Finance.date(item.date).getUTCMonth() / 3) + 1} ${item.date.slice(0, 4)}`; if (scale === 'week') return `${shortDate(item.date < period.start ? period.start : item.date)} – ${shortDate(item.end)}`; return shortDate(item.date); }
  function setChart(id, option, table, click) {
    chartTables.set(id, table); const element = document.getElementById(`chart-${id}`); if (!element || !element.getClientRects().length) return;
    let instance = chartRegistry.get(id);
    if (!instance) { instance = echarts.init(element, null, { renderer: 'svg' }); chartRegistry.set(id, instance); element.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); showChartTable(id); } if (['ArrowLeft', 'ArrowRight'].includes(event.key)) { event.preventDefault(); const count = instance.getOption().xAxis?.[0]?.data?.length || 0; if (!count) return; const cursor = Math.max(0, Math.min(count - 1, Number(element.dataset.cursor || 0) + (event.key === 'ArrowLeft' ? -1 : 1))); element.dataset.cursor = cursor; instance.dispatchAction({ type: 'showTip', seriesIndex: 0, dataIndex: cursor }); } if (event.key === 'Escape') instance.dispatchAction({ type: 'hideTip' }); }); }
    instance.resize(); instance.setOption({ animation: !matchMedia('(prefers-reduced-motion: reduce)').matches, animationDuration: 0, animationDurationUpdate: 220, textStyle: { fontFamily: 'DM Sans', color: '#626779', fontSize: 11 }, aria: { enabled: false }, ...option }, { replaceMerge: ['series'] }); instance.off('click'); if (click) instance.on('click', click);
  }
  function timeChart(id, value, color, title, type = 'bar') {
    type = layout.variants[id] || type;
    const scale = grain(id), data = Finance.metrics(state, context(scale)), labels = data.series.map(item => bucketLabel(item, scale));
    const points = data.series.map(item => value(item));
    setChart(id, { ...axes(labels), yAxis: { ...axes([]).yAxis, scale: type === 'line' }, series: [{ name: title, type, data: points.map(amount => amount === null ? null : amount / 100), showSymbol: points.filter(amount => amount !== null).length === 1, connectNulls: false, barMaxWidth: 32, itemStyle: { color, borderRadius: type === 'bar' ? [3, 3, 0, 0] : 0 }, lineStyle: { color, width: 2.5 }, areaStyle: type === 'line' ? { color: '#325cf414' } : undefined }] }, { headers: ['Intervalle', title], rows: data.series.map((item, index) => [labels[index], money(points[index])]) }, item => { const group = data.series[item.dataIndex]; if (group) { const start = group.date < period.start ? period.start : group.date; showDetail(id, labels[item.dataIndex], id === 'balance' ? Finance.selectedRows(state, { start, end: group.end, scope }) : rowsFor(start, group.end)); } });
  }
  function drawCharts(only = '') {
    const needed = id => (!only || only === id) && !!document.getElementById(`chart-${id}`);
    if (needed('envelope-rings')) { const all = Finance.budgetSummary(state, context()).envelopes, items = view === 'today' ? all.slice(0, 5) : all, step = 70 / Math.max(1, items.length); setChart('envelope-rings', { tooltip: { show: false }, series: items.map((item, index) => ({ name: item.category, type: 'pie', radius: [`${94 - index * step - step * .64}%`, `${94 - index * step}%`], label: { show: false }, emphasis: { scale: false }, data: [{ name: item.category, value: Math.min(item.spent, Math.max(item.limit, item.spent)), itemStyle: { color: palette[index % palette.length] } }, { name: 'Disponible', value: Math.max(0, item.limit - item.spent) || (item.spent ? 0 : 1), itemStyle: { color: '#e9edf5' } }] })) }, { headers: ['Enveloppe', 'Dépensé', 'Plafond', 'Disponible'], rows: items.map(item => [item.category, money(item.spent), money(item.limit), money(item.remaining)]) }, item => { const category = items[item.seriesIndex]?.category; if (category) { auxiliary = { type: 'budget', id: category }; render(); } }); }
    if (needed('balance')) timeChart('balance', item => item.balance, palette[0], 'Solde', 'line');
    if (needed('expenses')) timeChart('expenses', item => item.expenses, palette[1], 'Dépenses');
    if (needed('week')) {
      const week = weekData(), dates = Array.from({ length: 7 }, (_, index) => Finance.addDays(week.start, index)), accounts = Finance.selectedAccounts(state, scope);
      const covered = value => accounts.length > 0 && accounts.every(item => item.openingDate <= value && item.throughDate >= value);
      const current = dates.map(value => value > week.end || !covered(value) ? null : -week.rows.filter(row => row.date === value).reduce((sum, row) => sum + row.amount, 0) / 100);
      const previous = dates.map(value => value > week.end || !covered(Finance.addDays(value, -7)) ? null : -week.previous.filter(row => row.date === Finance.addDays(value, -7)).reduce((sum, row) => sum + row.amount, 0) / 100);
      setChart('week', { ...axes(dates.map(value => new Intl.DateTimeFormat('fr-FR', { weekday: 'short', timeZone: 'UTC' }).format(Finance.date(value)))), series: [{ name: 'Semaine précédente', type: 'bar', data: previous, itemStyle: { color: '#b7c7ff', borderRadius: [3, 3, 0, 0] }, barMaxWidth: 20 }, { name: week.label === 'Dépensé cette semaine' ? 'Cette semaine' : 'Semaine couverte', type: 'bar', data: current, itemStyle: { color: palette[1], borderRadius: [3, 3, 0, 0] }, barMaxWidth: 20 }] }, { headers: ['Jour', 'Semaine couverte', 'Même jour précédent'], rows: dates.map((value, index) => [fullDate(value), current[index] === null ? value > week.end ? 'À venir' : 'Non couvert' : money(Math.round(current[index] * 100)), previous[index] === null ? 'Non couvert' : money(Math.round(previous[index] * 100))]) }, item => showDetail('week', fullDate(dates[item.dataIndex]), rowsFor(dates[item.dataIndex], dates[item.dataIndex])));
    }
    for (const id of ['categories', 'analysis-categories']) if (needed(id)) { const data = Finance.metrics(state, context()); setChart(id, { tooltip: { show: false }, series: [{ type: 'pie', radius: ['64%', '82%'], center: ['50%', '50%'], color: palette, label: { show: false }, emphasis: { label: { show: false }, scaleSize: 3 }, itemStyle: { borderColor: '#fff', borderWidth: 3, borderRadius: 3 }, data: data.categories.map(item => ({ name: item.name, value: item.amount / 100 })) }] }, { headers: ['Catégorie', 'Dépenses'], rows: data.categories.map(item => [item.name, money(item.amount)]) }, item => showDetail(id, item.name, rowsFor().filter(row => row.category === item.name))); const chart = chartRegistry.get(id); chart.off('mouseover'); chart.off('globalout'); chart.on('mouseover', item => ringValue(id, item.name, Math.round(item.value * 100))); chart.on('globalout', () => ringValue(id, 'Dépenses', data.expenses)); ringValue(id, 'Dépenses', data.expenses); }
    if (needed('merchants')) { const totals = new Map(); for (const row of rowsFor()) totals.set(row.merchant, (totals.get(row.merchant) || 0) - row.amount); const items = [...totals].sort((first, second) => second[1] - first[1]).slice(0, 7).reverse(); setChart('merchants', { tooltip, grid: { left: 4, right: 18, top: 4, bottom: 8, containLabel: true }, xAxis: { type: 'value', name: privacy ? '' : '€', axisLabel: { formatter: value => privacy ? '•••' : value, fontSize: 10 }, splitLine: { lineStyle: { type: 'dashed', color: '#eceff7' } } }, yAxis: { type: 'category', data: items.map(item => item[0]), axisTick: { show: false }, axisLine: { show: false }, axisLabel: { width: 110, overflow: 'truncate', fontSize: 11 } }, series: [{ name: 'Dépenses', type: 'bar', data: items.map(item => item[1] / 100), barMaxWidth: 18, itemStyle: { color: palette[0], borderRadius: [0, 3, 3, 0] } }] }, { headers: ['Marchand', 'Dépenses'], rows: items.map(item => [item[0], money(item[1])]) }, item => showDetail('merchants', item.name, rowsFor().filter(row => row.merchant === item.name))); }
    if (needed('budget-pace')) { const data = Finance.metrics(state, context(grain('budget-pace'))), budget = Finance.budgetSummary(state, context()), allowanceByDay = new Map(); let accumulated = 0, allowance = 0; for (const value of Finance.days(period.start, period.end)) { const parsed = Finance.date(value), monthDays = new Date(Date.UTC(parsed.getUTCFullYear(), parsed.getUTCMonth() + 1, 0)).getUTCDate(); allowance += budget.monthly / monthDays; allowanceByDay.set(value, Math.round(allowance) / 100); } const labels = data.series.map(item => bucketLabel(item, grain('budget-pace'))), spent = data.series.map(item => { accumulated += item.expenses; return accumulated / 100; }), limits = data.series.map(item => allowanceByDay.get(item.end)); setChart('budget-pace', { ...axes(labels), series: [{ name: 'Dépenses cumulées', type: 'line', showSymbol: data.series.length === 1, data: spent, lineStyle: { color: palette[1], width: 2.5 }, itemStyle: { color: palette[1] } }, { name: 'Plafond proratisé', type: 'line', showSymbol: data.series.length === 1, data: limits, lineStyle: { color: palette[0], type: 'dashed', width: 2 }, itemStyle: { color: palette[0] } }] }, { headers: ['Date', 'Dépenses cumulées', `Budget ${money(budget.monthly)}/mois`], rows: labels.map((label, index) => [label, money(Math.round(spent[index] * 100)), money(Math.round(limits[index] * 100))]) }); }
    if (needed('accounts')) { const scale = grain('accounts'), data = Finance.metrics(state, context(scale)), accounts = Finance.selectedAccounts(state, scope), labels = data.series.map(item => bucketLabel(item, scale)); const series = accounts.map((item, index) => ({ name: item.name, type: data.series.length === 1 ? 'bar' : 'line', showSymbol: false, connectNulls: false, barMaxWidth: 24, itemStyle: { color: palette[index % palette.length] }, lineStyle: { color: palette[index % palette.length], width: 2 }, data: data.series.map(group => group.end <= item.throughDate ? Finance.balance(state, item.id, group.end) : null).map(value => value === null ? null : value / 100) })); setChart('accounts', { ...axes(labels), yAxis: { ...axes([]).yAxis, scale: true }, legend: { bottom: 0, type: 'scroll', textStyle: { fontSize: 11 } }, grid: { ...axes([]).grid, bottom: 42 }, series }, { headers: ['Date', ...accounts.map(item => item.name)], rows: labels.map((label, index) => [label, ...series.map(item => item.data[index] === null ? 'Non couvert' : money(Math.round(item.data[index] * 100)))]) }); }
    if (needed('recurring-history')) { const recurringRows = new Set(detected().flatMap(item => item.rows.map(row => row.id))); timeChart('recurring-history', group => -rowsFor(group.date < period.start ? period.start : group.date, group.end).filter(row => recurringRows.has(row.id)).reduce((sum, row) => sum + row.amount, 0), palette[0], 'Débits récurrents observés'); }
  }
  function showDetail(id, title, rows) { request(() => { selections.set(id, { title, rows: [...rows].sort((first, second) => second.date.localeCompare(first.date)) }); render(); document.querySelector(`#component-${id} .detail-head button`)?.focus({ preventScroll: true }); }); }
  function showChartTable(id) { const target = document.getElementById(`table-${id}`), table = chartTables.get(id); if (!target || !table) return; target.hidden = !target.hidden; if (!target.hidden) target.innerHTML = `<div class="table-scroll"><table><thead><tr>${table.headers.map(name => `<th>${safe(name)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row => `<tr>${row.map(value => `<td>${safe(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
  function envelopeActions() { return `<div class="tools envelope-modes">${[['bars', 'Barres', 'chart-no-axes-gantt'], ['rings', 'Anneaux', 'circle-dot'], ['table', 'Tableau', 'table-2']].map(([key, label, glyph]) => iconButton('envelope-mode', label, glyph, `data-value="${key}" aria-pressed="${(layout.variants.envelopes || 'bars') === key}"`)).join('')}</div>`; }
  function request(action) { if (editor?.dirty) { pendingAction = action; render(); const warning = [...main.querySelectorAll('.inline-warning')].find(element => element.getClientRects().length); warning?.scrollIntoView({ block: 'center' }); warning?.querySelector('button')?.focus({ preventScroll: true }); return; } action(); }
  function closeEditors() { if (editor) drafts.delete(`transaction:${editor.id}`); if (auxiliary) drafts.clear(); editor = null; auxiliary = null; customizing = false; }
  function go(route, push = true) { request(() => { if (!routes[route]) route = 'today'; if (route !== view) closeEditors(); scrollPositions.set(view, window.scrollY); view = route; if (push && location.hash !== `#${route}`) history.pushState(null, '', `#${route}`); document.getElementById('more-menu').hidden = true; document.getElementById('more-trigger').setAttribute('aria-expanded', 'false'); render(); window.scrollTo({ top: scrollPositions.get(route) || 0, behavior: 'instant' }); main.focus({ preventScroll: true }); }); }
  function readImport() {
    if (!importDraft) return;
    const value = (id, fallback) => document.getElementById(id)?.value ?? fallback;
    Object.assign(importDraft, { account: value('import-account', importDraft.account), accountName: value('new-account-name', importDraft.accountName), owner: value('new-account-owner', importDraft.owner), openingDate: value('new-opening-date', importDraft.openingDate), openingText: value('new-opening', importDraft.openingText), closingDate: value('closing-date', importDraft.closingDate), closingText: value('closing-balance', importDraft.closingText), includeDuplicates: document.getElementById('include-duplicates')?.checked || false });
  }
  async function readWorkbook(file) {
    const zip = await window.JSZip.loadAsync(await file.arrayBuffer()), parser = new DOMParser();
    const nodes = (document, name) => [...document.getElementsByTagNameNS('*', name)];
    const xml = async path => {
      const entry = zip.file(path); if (!entry) throw new Error('Classeur XLSX incomplet.');
      const content = await entry.async('string'); if (content.length > 40 * 1024 * 1024) throw new Error('Feuille Excel trop volumineuse.');
      const document = parser.parseFromString(content.replace(/^\uFEFF/, ''), 'application/xml');
      if (nodes(document, 'parsererror').length) throw new Error('Structure XML du classeur invalide.');
      return document;
    };
    const strings = zip.file('xl/sharedStrings.xml') ? nodes(await xml('xl/sharedStrings.xml'), 'si').map(item => item.textContent) : [];
    const book = await xml('xl/workbook.xml'), relations = nodes(await xml('xl/_rels/workbook.xml.rels'), 'Relationship');
    const sheet = nodes(book, 'sheet').find(item => item.getAttribute('name')?.trim().toLowerCase() === 'transactions');
    if (!sheet) throw new Error('Le classeur doit contenir une feuille Transactions.');
    const id = sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships', 'id');
    const target = relations.find(item => item.getAttribute('Id') === id)?.getAttribute('Target');
    if (!target) throw new Error('Feuille Transactions introuvable dans le classeur.');
    const document = await xml(target.startsWith('/') ? target.slice(1) : `xl/${target}`);
    const rows = nodes(document, 'row').map(row => Object.fromEntries(nodes(row, 'c').map(cell => [cell.getAttribute('r')?.match(/^[A-Z]+/)?.[0], cell.getAttribute('t') === 's' ? strings[Number(nodes(cell, 'v')[0]?.textContent)] : nodes(cell, 'is')[0]?.textContent || nodes(cell, 'v')[0]?.textContent || ''])));
    const headerIndex = rows.findIndex(row => Object.values(row).some(value => String(value).trim().toLowerCase() === 'date'));
    if (headerIndex < 0) throw new Error('En-tête Date introuvable dans Transactions.');
    const header = Object.entries(rows[headerIndex]).filter(([, value]) => String(value).trim()).map(([column, value]) => [column, String(value).trim()]);
    const fields = header.map(([, name]) => name);
    if (new Set(fields).size !== fields.length) throw new Error('Le classeur contient des en-têtes en double.');
    const dateField = fields.find(name => name.toLowerCase() === 'date');
    const epoch = nodes(book, 'workbookPr').some(item => ['1', 'true'].includes(item.getAttribute('date1904'))) ? Date.UTC(1904, 0, 1) : Date.UTC(1899, 11, 30);
    const data = rows.slice(headerIndex + 1).map(row => Object.fromEntries(header.map(([column, name]) => [name, row[column] || '']))).filter(row => row[dateField]);
    if (data.length > 100000) throw new Error('Import limité à 100 000 opérations.');
    for (const row of data) if (/^\d+(?:\.\d+)?$/.test(row[dateField])) row[dateField] = new Date(epoch + Number(row[dateField]) * 86400000).toISOString().slice(0, 10);
    return { data, meta: { fields }, errors: [] };
  }
  function prepareImport(file) {
    if (!file) return; if (file.size > 20 * 1024 * 1024) throw new Error('Relevé limité à 20 Mo.');
    if (!/\.(csv|xlsx)$/i.test(file.name)) throw new Error('Choisir un fichier CSV ou XLSX.');
    const sequence = ++importSequence;
    const complete = result => { if (sequence === importSequence) stageImport(file, result); };
    const failed = error => { if (sequence === importSequence) notify(error.message, true); };
    if (/\.xlsx$/i.test(file.name)) { readWorkbook(file).then(complete).catch(failed); return; }
    Papa.parse(file, { header: true, skipEmptyLines: 'greedy', transformHeader: name => name.trim().replace(/^\uFEFF/, ''), complete, error: failed });
  }
  function stageImport(file, result) {
      if (result.errors.length) { notify(result.errors[0].message, true); return; }
      const fields = result.meta.fields || [], mapping = {}, aliases = { date: ['date', 'date opération', 'date operation'], merchant: ['libellé', 'libelle', 'merchant', 'marchand', 'description', 'detail', 'label'], amount: ['amount', 'montant'], debit: ['debit', 'débit'], credit: ['credit', 'crédit'], direction: ['direction', 'type', 'sens'], category: ['category', 'catégorie', 'categorie'], status: ['status', 'statut'], bankLabel: ['bank_label', 'libellé', 'libelle'], bankDetail: ['detail', 'détail'], internal: ['is_internal', 'interne'], shared: ['shared', 'partagé', 'partage'], sourceId: ['source_id', 'id'] };
      for (const [key, names] of Object.entries(aliases)) mapping[key] = fields.find(name => names.includes(name.toLocaleLowerCase('fr'))) || '';
      const dates = result.data.map(row => { try { return Finance.csvDate(row[mapping.date]); } catch { return null; } }).filter(Boolean).sort();
      const sourceField = fields.find(name => ['compte', 'account', 'iban'].includes(name.toLowerCase())), sources = sourceField ? [...new Set(result.data.map(row => row[sourceField]).filter(Boolean))] : [];
      const sourceKey = sources[0] || '', known = sourceKey ? state.accounts.find(item => item.sourceKey === sourceKey) : null;
      importDraft = { allRaw: result.data, raw: result.data, sourceField, sources, fields, mapping, name: file.name, sourceKey, account: known?.id || 'new', accountId: crypto.randomUUID(), accountName: sourceKey || file.name.replace(/\.(csv|xlsx)$/i, '').replace(/[_-]/g, ' '), owner: 'a', openingDate: dates[0] || period.start, openingText: '', closingDate: dates.at(-1) || period.end, closingText: '', includeDuplicates: false, review: null }; selectImportSource(sourceKey); render();
  }
  function checkImport() {
    readImport(); if (!importDraft) throw new Error('Choisir un fichier CSV.');
    const draft = importDraft, mapping = draft.mapping; if (!mapping.date || !mapping.merchant || !mapping.amount && !mapping.debit && !mapping.credit) throw new Error('Associer date, libellé et montant ou débit/crédit.');
    Finance.date(draft.closingDate);
    const staged = draft.account === 'new' ? { id: draft.accountId, name: draft.accountName.trim(), owner: draft.owner, sourceKey: draft.sourceKey, openingDate: draft.openingDate, throughDate: draft.closingDate, opening: Finance.parseAmount(draft.openingText) } : null;
    if (staged && !staged.name) throw new Error('Nommer le compte identifié par le CSV.');
    const candidate = staged ? { ...state, accounts: [...state.accounts, staged] } : state; Finance.validateState(candidate);
    const accountId = staged?.id || draft.account, targetAccount = staged || account(accountId); if (!targetAccount) throw new Error('Choisir le compte du relevé.');
    const result = Finance.normalizeRows(draft.raw, mapping, accountId), known = new Set(state.transactions.map(Finance.fingerprint)), rows = []; let duplicates = 0;
    for (const row of result.rows) { if (row.date < targetAccount.openingDate || row.date > draft.closingDate) result.errors.push({ line: draft.raw.findIndex(raw => String(raw[mapping.merchant]).trim() === row.bankLabel) + 2, message: 'Date hors du point de départ et de la fin du relevé.' }); const key = Finance.fingerprint(row); if (known.has(key) && !draft.includeDuplicates) { duplicates++; continue; } known.add(key); const previous = state.transactions.find(item => item.account === accountId && item.bankLabel === row.bankLabel); if (previous) Object.assign(row, { merchant: previous.merchant, category: previous.category, shared: previous.shared, splitMode: previous.splitMode, splitA: previous.splitA, recurrence: previous.recurrence, recurrenceFrequency: previous.recurrenceFrequency }); rows.push(row); }
    const control = draft.closingText.trim() ? Finance.reconciliation(candidate, accountId, rows, draft.closingDate, Finance.parseAmount(draft.closingText)) : null;
    draft.review = { rows, duplicates, errors: result.errors, control, account: staged }; render();
  }
  function selectImportSource(sourceKey) {
    const draft = importDraft, known = state.accounts.find(item => sourceKey && item.sourceKey === sourceKey);
    draft.sourceKey = sourceKey; draft.raw = draft.sourceField ? draft.allRaw.filter(row => row[draft.sourceField] === sourceKey) : draft.allRaw;
    const dates = draft.raw.flatMap(row => { try { return [Finance.csvDate(row[draft.mapping.date])]; } catch { return []; } }).sort();
    Object.assign(draft, { account: known?.id || 'new', accountId: crypto.randomUUID(), accountName: sourceKey || draft.name.replace(/\.(csv|xlsx)$/i, '').replace(/[_-]/g, ' '), owner: known?.owner || 'a', openingDate: dates[0] || period.start, closingDate: dates.at(-1) || period.end, openingText: '', closingText: '', includeDuplicates: false, review: null });
  }
  function commitImport() {
    const review = importDraft?.review; if (!review || review.errors.length || review.control?.difference || !review.rows.length || state.mode === 'demo') throw new Error('Le contrôle doit être valide avant import.');
    const first = review.rows.reduce((earliest, row) => row.date < earliest ? row.date : earliest, review.rows[0].date), last = review.rows.reduce((latest, row) => row.date > latest ? row.date : latest, review.rows[0].date);
    commit(next => { if (review.account) next.accounts.push({ ...review.account, throughDate: review.control ? importDraft.closingDate : last }); next.transactions.push(...review.rows); const target = next.accounts.find(item => item.id === (review.account?.id || importDraft.account)); const through = review.control ? importDraft.closingDate : last; if (target.throughDate < through) target.throughDate = through; });
    const count = review.rows.length; importDraft = null; period = { start: first, end: last }; preset = 'custom'; scope = 'all'; selections.clear(); go('history'); notify(`${count} opérations importées. Récurrences et partage recalculés.`);
  }
  function saveForm(form) {
    const values = new FormData(form), type = form.dataset.form, id = form.dataset.id;
    if (type === 'transaction') {
      const row = state.transactions.find(item => item.id === id), kind = values.get('kind'), mode = values.get('allocation');
      if (kind === 'income' && row.amount < 0 || kind === 'expense' && row.amount > 0) throw new Error('Nature incompatible avec le signe du montant CSV.');
      const splitA = mode === 'a' ? 100 : mode === 'b' ? 0 : mode === 'custom' ? Number(values.get('splitA')) : Finance.incomeRatio(state, context()).ratio;
      if (!Number.isFinite(splitA) || splitA < 0 || splitA > 100) throw new Error('Pourcentage entre 0 et 100.');
      const previousEditor = editor; editor = null; pendingAction = null; drafts.delete(`transaction:${id}`);
      try { commit(next => Object.assign(next.transactions.find(item => item.id === id), { merchant: String(values.get('merchant')).trim(), category: values.get('category'), kind, shared: mode !== 'personal', splitMode: mode === 'auto' ? 'auto' : 'manual', splitA, recurrence: values.get('recurrence'), recurrenceFrequency: values.get('recurrence') === 'include' ? values.get('recurrenceFrequency') : undefined, note: String(values.get('note')) })); } catch (error) { editor = previousEditor; throw error; }
      [...main.querySelectorAll('[data-action="edit-transaction"]')].find(element => element.dataset.id === id && element.getClientRects().length)?.focus({ preventScroll: true });
      notify('Annotation enregistrée · montant bancaire inchangé.'); return;
    }
    if (type === 'budget' || type === 'overall') { const amount = Finance.parseAmount(values.get('amount')); if (amount < 0) throw new Error('Plafond positif ou nul.'); commit(next => { if (type === 'overall') next.monthlyBudget = amount; else { if (id && id !== values.get('category')) delete next.budgets[id]; next.budgets[values.get('category')] = amount; } }); }
    if (type === 'account') { const openingDate = values.get('openingDate'), opening = Finance.parseAmount(values.get('opening')); Finance.date(openingDate); const through = account(id).throughDate; if (openingDate > through) throw new Error('Le point de départ doit précéder la couverture du CSV.'); commit(next => Object.assign(next.accounts.find(item => item.id === id), { name: String(values.get('name')).trim(), owner: values.get('owner'), openingDate, opening })); }
    if (type === 'household' || type === 'personal') { const household = { a: String(values.get('a')).trim(), b: String(values.get('b')).trim(), ratio: Number(values.get('ratio')) }; commit(next => { next.household = household; if (type === 'personal') { Object.assign(next, { mode: 'personal', accounts: [], transactions: [], recurring: [], budgets: {} }); delete next.monthlyBudget; } }); }
    drafts.delete(`${type}:${id || ''}`); auxiliary = null; render(); if (type === 'personal') { period = Finance.range('month', reference()); go('import'); } else notify('Enregistré.');
  }
  document.addEventListener('click', event => {
    const target = event.target.closest('button,a'); if (!target) return;
    try {
      if (target.matches('a[href^="#"]') && target.getAttribute('href') !== '#main') { event.preventDefault(); go(target.getAttribute('href').slice(1)); return; }
      if (target.dataset.grain) { grains[target.dataset.chart] = target.dataset.grain === 'auto' ? undefined : target.dataset.grain; const group = target.closest('.chart-mode'); for (const item of group.querySelectorAll('button')) item.setAttribute('aria-pressed', String(item === target)); drawCharts(target.dataset.chart); return; }
      if (target.dataset.historyType) { request(() => { closeEditors(); historyType = target.dataset.historyType; pageIndex = 0; render(); }); return; }
      if (target.id === 'more-trigger') { const menu = document.getElementById('more-menu'); menu.hidden = !menu.hidden; target.setAttribute('aria-expanded', String(!menu.hidden)); return; }
      const actions = {
        'previous-week': () => request(() => { weekOffset--; selections.delete('week'); render(); }), 'next-week': () => request(() => { weekOffset = Math.min(0, weekOffset + 1); selections.delete('week'); render(); }),
        'envelope-mode': () => request(() => saveLayout(next => { next.variants.envelopes = target.dataset.value; })),
        'customize-dashboard': () => request(() => { customizing = !customizing; render(); }),
        'hide-widget': () => request(() => { selections.delete(target.dataset.widget); closeEditors(); customizing = true; saveLayout(next => { if (next[view].length > 1) next[view] = next[view].filter(id => id !== target.dataset.widget); }); }),
        'move-widget': () => saveLayout(next => { const index = next[view].indexOf(target.dataset.widget), destination = index + Number(target.dataset.step); if (destination >= 0 && destination < next[view].length) [next[view][index], next[view][destination]] = [next[view][destination], next[view][index]]; }),
        'reset-layout': () => saveLayout(next => { next[view] = [...defaultLayout[view]]; for (const id of availableWidgets[view]) { delete next.widths[id]; delete next.variants[id]; } }),
        privacy: () => { privacy = !privacy; target.setAttribute('aria-pressed', String(privacy)); target.setAttribute('aria-label', privacy ? 'Afficher les montants' : 'Masquer les montants'); target.title = target.getAttribute('aria-label'); render(); },
        import: () => go('import'), 'previous-period': () => request(() => { closeEditors(); period = Finance.shiftPeriod(period, -1); preset = 'custom'; selections.clear(); pageIndex = 0; render(); }), 'next-period': () => request(() => { closeEditors(); period = Finance.shiftPeriod(period, 1); preset = 'custom'; selections.clear(); pageIndex = 0; render(); }),
        'edit-transaction': () => request(() => { editor = { id: target.dataset.id, host: target.dataset.host, dirty: false }; render(); [...main.querySelectorAll(`form[data-form="transaction"][data-id="${CSS.escape(editor.id)}"] input`)].find(element => element.getClientRects().length)?.focus({ preventScroll: true }); }),
        'cancel-edit': () => request(() => { if (editor) drafts.delete(`transaction:${editor.id}`); const id = editor?.id; editor = null; render(); [...main.querySelectorAll('[data-action="edit-transaction"]')].find(element => element.dataset.id === id && element.getClientRects().length)?.focus({ preventScroll: true }); }),
        'keep-edit': () => { pendingAction = null; render(); }, 'discard-edit': () => { const action = pendingAction; if (editor) drafts.delete(`transaction:${editor.id}`); editor = null; pendingAction = null; action?.(); },
        'close-detail': () => request(() => { closeEditors(); selections.delete(target.dataset.component); render(); document.querySelector(`#component-${target.dataset.component} button`)?.focus({ preventScroll: true }); }),
        'category-detail': () => showDetail(target.dataset.component, target.dataset.category, rowsFor().filter(row => row.category === target.dataset.category)), 'day-detail': () => showDetail('days', fullDate(target.dataset.day), rowsFor(target.dataset.day, target.dataset.day)), 'unclassified-detail': () => showDetail('quality', 'Dépenses à classer', rowsFor().filter(row => row.category === 'À classer')),
        'chart-table': () => showChartTable(target.dataset.chart), 'previous-page': () => request(() => { closeEditors(); pageIndex--; render(); }), 'next-page': () => request(() => { closeEditors(); pageIndex++; render(); }),
        'edit-budget': () => request(() => { if (!['today', 'budget'].includes(view)) go('budget'); auxiliary = { type: 'budget', id: target.dataset.category }; render(); }), 'new-budget': () => request(() => { auxiliary = { type: 'budget', id: '' }; render(); }), 'edit-overall': () => request(() => { auxiliary = { type: 'overall' }; render(); }), 'remove-budget': () => { commit(next => { delete next.budgets[target.dataset.category]; }); auxiliary = null; render(); }, 'close-auxiliary': () => { const form = target.closest('form'); if (form) drafts.delete(`${form.dataset.form}:${form.dataset.id || ''}`); auxiliary = null; render(); },
        'edit-account': () => { auxiliary = { type: 'account', id: target.dataset.id }; render(); }, 'edit-household': () => { auxiliary = { type: 'household' }; render(); }, 'start-personal': () => request(() => { if (!['settings', 'import'].includes(view)) go('settings'); auxiliary = { type: 'personal' }; render(); }),
        'recurring-detail': () => request(() => { const item = detected()[Number(target.dataset.index)]; if (item) { auxiliary = { type: 'recurring-review', id: item.rows.at(-1).id }; showDetail('recurring-list', `${item.name} · ${item.rows.length} débits CSV`, item.rows); main.querySelector('.recurring-review')?.scrollIntoView({ block: 'center' }); } }), 'exclude-recurring': () => request(() => { const id = target.dataset.id; closeEditors(); selections.delete('recurring-list'); commit(next => { const row = next.transactions.find(item => item.id === id); if (row) row.recurrence = 'exclude'; }); notify('Récurrent écarté · paiements conservés dans l’historique.'); }), 'reconsider-recurring': () => { const source = state.transactions.find(row => row.id === target.dataset.id); commit(next => { for (const row of next.transactions) if (row.account === source.account && row.merchant === source.merchant) row.recurrence = 'auto'; }); notify('Suivi rétabli.'); },
        'check-import': checkImport, 'commit-import': commitImport,
        backup: () => download(`wealthpilot-${Finance.iso(new Date())}.json`, JSON.stringify(state, null, 2), 'application/json'), restore: () => document.getElementById('restore-file').click(), 'cancel-restore': () => { restoreCandidate = null; render(); }, 'confirm-restore': () => { if (!restoreCandidate) return; localStorage.setItem(storageKey, JSON.stringify(restoreCandidate)); state = restoreCandidate; loadError = null; restoreCandidate = null; scope = 'all'; editor = null; auxiliary = null; selections.clear(); drafts.clear(); render(); notify('Sauvegarde restaurée.'); },
        'export-csv': () => download(`transactions-${period.start}-${period.end}.csv`, Papa.unparse(filteredRows().map(row => ({ date: row.date, merchant: row.merchant, bank_label: row.bankLabel, amount: (row.amount / 100).toFixed(2), account: account(row.account)?.name, category: row.category, type: row.kind, status: row.status })), { escapeFormulae: true }), 'text/csv;charset=utf-8')
      };
      actions[target.dataset.action]?.();
    } catch (error) { notify(error.message, true); }
  });
  document.addEventListener('submit', event => { const form = event.target.closest('form[data-form]'); if (!form) return; event.preventDefault(); try { saveForm(form); } catch (error) { const message = form.querySelector('.error'); if (message) message.textContent = error.message; else notify(error.message, true); } });
  document.addEventListener('input', event => {
    if (event.target.closest('form[data-form="transaction"]') && editor) editor.dirty = true;
    if (event.target.id === 'search') { const value = event.target.value, caret = event.target.selectionStart; request(() => { closeEditors(); query = value; pageIndex = 0; render(); const input = document.getElementById('search'); input.focus(); input.setSelectionRange(caret, caret); }); }
    if (view === 'import' && importDraft && event.target.matches('#closing-balance,#new-opening,#new-account-name')) { readImport(); importDraft.review = null; document.querySelector('[data-action="commit-import"]')?.setAttribute('disabled', ''); }
  });
  document.addEventListener('change', event => {
    try {
      const target = event.target;
      if (target.dataset.widgetToggle) request(() => { const id = target.dataset.widgetToggle; closeEditors(); customizing = true; selections.delete(id); saveLayout(next => { if (target.checked) next[view].push(id); else if (next[view].length > 1) next[view] = next[view].filter(item => item !== id); }); });
      if (target.dataset.widgetWidth) saveLayout(next => { if (target.value) next.widths[target.dataset.widgetWidth] = Number(target.value); else delete next.widths[target.dataset.widgetWidth]; });
      if (target.dataset.widgetVariant) saveLayout(next => { next.variants[target.dataset.widgetVariant] = target.value; });
      if (target.id === 'source-account' && importDraft) { selectImportSource(target.value); render(); }
      if (target.id === 'scope') request(() => { closeEditors(); scope = target.value; selections.clear(); pageIndex = 0; render(); });
      if (target.id === 'category-filter') request(() => { closeEditors(); categoryFilter = target.value; pageIndex = 0; render(); });
      if (target.id === 'period-preset') request(() => { closeEditors(); preset = target.value; if (preset !== 'custom') period = Finance.range(preset, reference()); selections.clear(); pageIndex = 0; render(); });
      if (target.id === 'period-start' || target.id === 'period-end') { const start = document.getElementById('period-start').value, end = document.getElementById('period-end').value; Finance.days(start, end); request(() => { closeEditors(); period = { start, end }; selections.clear(); render(); }); }
      if (target.name === 'allocation') { target.closest('form').querySelector('.custom-split').hidden = target.value !== 'custom'; if (editor) editor.dirty = true; }
      if (target.name === 'recurrence') target.closest('form').querySelector('.recurrence-frequency').hidden = target.value !== 'include';
      if (target.closest('form[data-form="transaction"]') && editor) editor.dirty = true;
      if (target.dataset.mapping && importDraft) { importDraft.mapping[target.dataset.mapping] = target.value; importDraft.review = null; document.querySelector('[data-action="commit-import"]')?.setAttribute('disabled', ''); }
      if (['import-account', 'closing-date', 'new-account-owner', 'new-opening-date', 'include-duplicates'].includes(target.id) && importDraft) { readImport(); importDraft.review = null; render(); }
      if (target.id === 'csv-file') prepareImport(target.files[0]);
      if (target.id === 'restore-file') { const file = target.files[0]; if (file && file.size <= 50 * 1024 * 1024) file.text().then(text => { restoreCandidate = Finance.validateState(JSON.parse(text)); if (view !== 'settings') go('settings'); else render(); }).catch(error => notify(error.message, true)); else throw new Error('Sauvegarde absente ou trop volumineuse.'); }
    } catch (error) { notify(error.message, true); }
  });
  document.addEventListener('keydown', event => { if (event.key !== 'Escape') return; document.getElementById('more-menu').hidden = true; document.getElementById('more-trigger').setAttribute('aria-expanded', 'false'); if (editor) { event.preventDefault(); request(() => { editor = null; render(); }); } });
  document.addEventListener('pointerdown', event => { if (!event.target.closest('#more-menu,#more-trigger')) { document.getElementById('more-menu').hidden = true; document.getElementById('more-trigger').setAttribute('aria-expanded', 'false'); } });
  window.addEventListener('popstate', () => { const next = location.hash.slice(1); if (editor?.dirty) history.replaceState(null, '', `#${view}`); go(next, false); });
  new ResizeObserver(() => { for (const instance of chartRegistry.values()) if (instance.getDom().getClientRects().length) instance.resize(); }).observe(main);
  matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change', () => drawCharts());
  document.fonts.ready.then(() => { for (const instance of chartRegistry.values()) instance.resize(); });
  go(location.hash.slice(1) || 'today', false);
  if (loadError) notify(`Données locales non chargées : ${loadError}. Aucune écriture autorisée avant restauration.`, true);
})();