import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Bike,
  Car,
  CarTaxiFront,
  Clapperboard,
  Coffee,
  Dumbbell,
  Fuel,
  Gamepad2,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Milestone,
  MonitorPlay,
  Package,
  Pill,
  PiggyBank,
  Plane,
  Receipt,
  RotateCcw,
  Sandwich,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquareParking,
  Tag,
  Ticket,
  TramFront,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { normalize } from "../../domain/search";

// French and English names (bank exports mix both). Most specific first:
// the subcategory is tested before the category.
const icons: [RegExp, LucideIcon][] = [
  [/fast ?food|burger|kebab|sandwich/, Sandwich],
  [/coffee|bakery|boulanger|cafe/, Coffee],
  [/grocer|course|supermarch|aliment/, ShoppingCart],
  [/deliver|livraison/, Bike],
  [/restau|resto|food/, UtensilsCrossed],
  [/insurance|assurance|mutuelle/, Shield],
  [/streaming|digital|software|logiciel/, MonitorPlay],
  [/bank fee|frais|commission|agios/, Receipt],
  [/benefit|allocation|caf\b|aide/, HandCoins],
  [/refund|rembours/, RotateCcw],
  [/salar|salaire|paie|income|revenu/, Banknote],
  [/cloth|vetement|habill|chaussure/, Shirt],
  [/online|en ligne|amazon/, Package],
  [/electronic|informatique/, Laptop],
  [/shopping|achat/, ShoppingBag],
  [/transit|transport en commun|navigo|train|metro|bus/, TramFront],
  [/ride|taxi|uber|vtc/, CarTaxiFront],
  [/fuel|carbur|essence/, Fuel],
  [/parking/, SquareParking],
  [/toll|peage/, Milestone],
  [/car care|garage|entretien|reparation/, Wrench],
  [/transport|voiture|auto/, Car],
  [/pharma/, Pill],
  [/health|medical|sante|medecin|soin/, HeartPulse],
  [/personal care|beaute|coiff|hygiene/, Sparkles],
  [/utilit|energie|electri|\beau\b|gaz/, Zap],
  [/rent|loyer|housing|logement|maison/, House],
  [/internet|box|wifi/, Wifi],
  [/mobile|telephone|telecom/, Smartphone],
  [/subscri|abonnement|bills|facture/, Receipt],
  [/sport|fitness|gym/, Dumbbell],
  [/cinema/, Clapperboard],
  [/event|concert|spectacle|sortie/, Ticket],
  [/entertain|loisir|jeu|game/, Gamepad2],
  [/transfer|virement|wero|p2p|joint|spouse/, ArrowLeftRight],
  [/child|enfant|creche|ecole|cantine|family|famille/, Baby],
  [/cash|atm|espece|retrait/, Wallet],
  [/tax|impot/, Landmark],
  [/saving|epargne/, PiggyBank],
  [/travel|voyage|vacance|hotel/, Plane],
];

/** Always an icon, never a letter: unknown categories get a tag. */
export function categoryIcon(category: string, subcategory = ""): LucideIcon {
  const names = [subcategory, category].map(normalize).filter(Boolean);
  for (const name of names) {
    const found = icons.find(([pattern]) => pattern.test(name))?.[1];
    if (found) return found;
  }
  return Tag;
}
